### ISSUE TITLE
automatically open browser on serve

### ISSUE THREAD

**Issue by bardiarastin** [jadjoubran/webdash-npm-scripts#10]
like other famous libraries we can open default browser of user and go to localhost:3456

**Comment by jadjoubran** [comment]
That would be cool 👍

**Comment by jadjoubran** [comment]
whoops, sorry
this belongs in the [main repo](https://github.com/jadjoubran/webdash) where `webdash serve` is written
I'll close this one here, feel free to create a new one there
Thanks!

**Comment by bardiarastin** [comment]
i created https://github.com/jadjoubran/webdash/issues/64
