### ISSUE TITLE
Refreshing the dashboard with background tasks

### ISSUE THREAD

**Issue by matthieudou** [jadjoubran/webdash-npm-scripts#6]
Hey, 

It's me again 😄 

One little problem (is it ?) is when running a background task (like `dev` server) and then refreshing the dashboard, the task doesn't seem to be running anymore. Even if it's still running in the background. The only way to `kill` it is manually with the pid or exiting webdash (not a problem)

**Comment by jadjoubran** [comment]
Awesome, thanks for noticing this @matthieudou 
I'll experiment and see if it's possible to keep track of commands spawn from webdash
then they would be cancelable on reload

**Comment by bardiarastin** [comment]
i'll take this one, pull request soon

**Comment by jadjoubran** [comment]
Awesome! 😄 Planning on using localStorage maybe?

**Comment by bardiarastin** [comment]
i believe using local storage is not good for this case, reasons: 
1: localstorage can be deleted by user and in incognito mode does not keep data
2: let's assume we're using it, processes on os can be terminated by a lot of reasons and browser thinks that process is still runing
...
here is my solution: 
we keep processes in backend, the browser at startup makes a request to api.js to see which processes are already ran before and adds loading to them + stop option

if you're good to go with this solution please let me know

**Comment by jadjoubran** [comment]
So if it's not localStorage then you have to store something on the disk? I'm not sure it's a good idea to write (other than the webdash.json config) on the user's disk..
I agree the localStorage is not optimal but it doesn't seem like a frequent scenario (clearing localStorage of localhost port 3456 or switching webdash from/to incognito)
+ It'd keep things easier to implement
What do you think? :d

**Comment by bardiarastin** [comment]
i was thinking about that actually there is no need we write on disk, when the user stops main webdash process, all children processes should be terminated, what do you think ?

**Comment by jadjoubran** [comment]
it wouldn't solve the browser reload issue though, since we can't know which ones are running

**Comment by bardiarastin** [comment]
okay i'll use localstorage but one question what happens if user would use webdash for multiple projects with same npm scripts ?

**Comment by jadjoubran** [comment]
we could use the `project name` as a prefix of the key in localStorage, for example:
`webdash-react-app-npm-scripts-dev`

where `webdash` is for `webdash` (the app)
`react-app` is the name of the end user's app (this is not possible yet, would require a fix from my side from PR)
`-npm-scripts` is the name of the plugin (webdash-npm-scripts)
`dev` is the name of the script running
.... but this is overcomplicated

because it's really an edge case that you switch webdash from project to project without closing the running script
(if it becomes a problem in the future, we can fix it)

**Comment by jadjoubran** [comment]
if you want a quick fix, you could simply say `webdash-npm-scripts-dev` to track that the script `dev` is running without prefixing it with the app name, as you wish

**Comment by bardiarastin** [comment]
#11 is here for this issue, main problem is that i tried to add loading spinner after startup but i could not do it :(((

**Comment by jadjoubran** [comment]
Alright I'll take a look thanks!
I'll probably commit on top of your PR
