### ISSUE TITLE
add linting to code base

### ISSUE THREAD

**Issue by bardiarastin** [jadjoubran/webdash-npm-scripts#9]
at the moment project does not use any linting libs, personally i suggest https://github.com/standard/standard

**Comment by jadjoubran** [comment]
Thanks @bardiarastin 
This would make more sense first in the main repo right?
[webdash](https://github.com/jadjoubran/webdash)
Is standard similar to prettier? I've been using prettier mostly but I don't have that mentioned in any configuration file

**Comment by bardiarastin** [comment]
Prettier is code formatter only, not linter, Standard is a set of eslint rules, some of them with autofix and it has a lot of plugins for popular code editors
should i open this in main repo too ?

**Comment by jadjoubran** [comment]
ah yeah you're right
Sounds great, yes please

**Comment by bardiarastin** [comment]
closing this as 81e75eb
